on: workflow_dispatch
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve secret
        env:
          command: ${{ secrets.COMMAND }}
        run: |
          echo "${command}"
